#ifndef BS_UTILS_H
#define BS_UTILS_H

#define PREP_KICKOFF_HOME 'K'
#define PREP_KICKOFF_AWAY 'k'
#define PREP_FREEKICK_HOME 'F'
#define PREP_FREEKICK_AWAY 'f'

#define START_KICKOFF_HOME PREP_KICKOFF_HOME + 128
#define START_KICKOFF_AWAY PREP_KICKOFF_AWAY + 128
#define START_FREEKICK_HOME PREP_FREEKICK_HOME + 128
#define START_FREEKICK_AWAY PREP_FREEKICK_AWAY + 128

#endif